version: '3'
services:
  web:
    build: .
    ports:
     - 127.0.0.1:8000:8000
    command: python manage.py runserver localhost:8000
    volumes:
      - .:/code

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - .:/data
