# Generated by Django 4.2.6 on 2023-11-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0002_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
