# Generated by Django 4.2.6 on 2023-11-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0003_counter_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='id',
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_id',
            field=models.CharField(default='carkey', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
